version: "3.8"

services:
  backend:
    build: ./server
    image: hamzamir7169/blog-app-backend:latest
    ports:
      - "5001:5000"
    environment:
      - PORT=5000

  frontend:
    build: ./client
    image: hamzamir7169/blog-app-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
